### ISSUE TITLE
Spectrum path is resolved inconsistantly

### ISSUE THREAD

**Issue by jnvsor** [Ciastex/Spectrum#3]
1c3b9f184197eba7b12e9467766c5f1e18b526b1 introduces a bug where Spectrum reads files from the correct place, but writes them to the wrong place.

Specifically, while spectrum files may be in `bin/Distance_Data/Spectrum/*` on linux, spectrum will write settings files to `Distance_Data/Spectrum/Settings`

**Edit:** You can add plugins to the list of folders it can't find. I'm guessing it needs to be updated everywhere

**Comment by Ciastex** [comment]
Bug fixed with commit 7594870.
