### ISSUE TITLE
'formatJson' parameter of Settings.Save doesn't do anything

### ISSUE THREAD

**Issue by Seeker14491** [Ciastex/Spectrum#30]
Saving the JSON pretty-printed should be supported, as it makes editing settings easier.

**Comment by REHERC** [comment]
I think the bug is back:

```csharp
Settings settings = new Settings("config");
settings["1"] = "test1";
settings["2"] = "test2";
settings.Save(true);
```

gives `{"1":"test1","2":"test2"}` (no formatting)

**Comment by Ciastex** [comment]
Ah, fuck, should be a quick fix.
