### ISSUE TITLE
I have this error when i start the "spectrum_install_windows.bat"

### ISSUE THREAD

**Issue by MasterAnakin99** [Ciastex/Spectrum#31]
"Unhandled Exception: System.UnauthorizedAccessException: Access denied 'Assembly-CSharp.dll.backup'.
   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite)
   en System.IO.File.Copy(String sourceFileName, String destFileName)
   en Spectrum.Prism.Program.CreateBackup()
   en Spectrum.Prism.Program.Main(String[] args)"

**Comment by Ciastex** [comment]
Amazing, thanks for the report, to aid you I need you to answer a few questions:
a) What version of Spectrum are you trying to install?
b) What path is `Assembly-CSharp.dll.backup` located at?
c) Have you tried using Resonator to install Spectrum instead?

**Comment by MasterAnakin99** [comment]
Hello Again. here you have the information you requested to me.
------
A) The last one, V0.2.2
B) C:\Program Files (x86)\Distance\Distance_Data\Managed
C) Yes, i tried to use the resonator but don't work... The resonator give me the same error when i tried.
------

- Sorry for the bad use of English that I have, I'm from Argentina.
