### ISSUE TITLE
[Feature Request] Server chat interactions

### ISSUE THREAD

**Issue by Elrontur** [Ciastex/Spectrum#8]
I thought of these features that would open up some possibilities for some server aspects:

- **Recieve chat messages** (Spectrum can read the sent messages of the host and other users)
- **Send chat messages** (Spectrum can send messages as the host user)
- **Command interpretion** (because Spectrum can recieve messages -> the next step)

**Comment by Ciastex** [comment]
Done, except the command interpretation, it's up to a plugin to receive events and process them.
